# -*- coding: utf-8 -*-
"""NER SHOPEE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haUZZdvjrmDvELZR4uKRfBGWNk_7HL_Z
"""

import json
import pandas as pd
import os
import re
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split
from google.colab import files

# =========================
# 0) Upload JSONL files
# =========================
uploaded = files.upload()

# Lấy tất cả file .jsonl trong /content
list_files = [os.path.join("/content", f) for f in os.listdir("/content") if f.endswith(".jsonl")]
print("Found jsonl files:", list_files)

# =========================
# 1) LABEL CONFIG (NEW)
# =========================
# Nhãn entity đúng như Doccano (label_name trong record['label'])
ENTITY_LABELS = [
    "KÍCH_THƯỚC",
    "MÀU_SẮC",
    "FORM",
    "CHẤT_LIỆU",
    "KỸ_THUẬT",
    "SHIP",
    "PRICE",
    "Ý_ĐỊNH",
    "CẢM_NHẬN",
]

# tạo label_list theo BIO: O + B- + I-
label_list = ["O"]
for ent in ENTITY_LABELS:
    label_list.append(f"B-{ent}")
    label_list.append(f"I-{ent}")

label2id = {l: i for i, l in enumerate(label_list)}
id2label = {i: l for l, i in label2id.items()}

print("Num labels:", len(label_list))
print("Labels:", label_list)

# =========================
# 2) Tokenizer (simple, split punctuation)
#    - token = word/number OR punctuation
# =========================
TOKEN_RE = re.compile(r"\w+|[^\w\s]", flags=re.UNICODE)

def merge_and_process_doccano(file_paths):
    all_tokens = []
    all_ner_ids = []
    all_texts = []
    all_ids = []

    seen_texts = set()

    print(f"🔄 Processing {len(file_paths)} file(s)...")

    for path in file_paths:
        if not os.path.exists(path):
            print(f"⚠️ Missing file: {path}")
            continue

        with open(path, "r", encoding="utf-8") as f:
            for line_no, line in enumerate(f, start=1):
                line = line.strip()
                if not line:
                    continue

                try:
                    record = json.loads(line)

                    # Doccano JSONL thường có: id, text, label, Comments
                    text = record.get("text", "")
                    spans = record.get("label", []) or []
                    rid = record.get("id", None)

                    text = text.strip()
                    if not text:
                        continue

                    # 1) dedupe by text
                    if text in seen_texts:
                        continue
                    seen_texts.add(text)

                    # 2) char-level BIO map
                    char_labels = ["O"] * len(text)

                    # --- xử lý overlap: ưu tiên span dài hơn trước,
                    # và chỉ ghi nếu vị trí đó còn là O (để tránh chồng nhãn)
                    # spans: [start, end, label_name]
                    clean_spans = []
                    for sp in spans:
                        if not isinstance(sp, (list, tuple)) or len(sp) < 3:
                            continue
                        start, end, label_name = sp[0], sp[1], sp[2]
                        if not isinstance(start, int) or not isinstance(end, int):
                            continue
                        if start < 0 or end <= start:
                            continue
                        if start >= len(text):
                            continue
                        label_name = str(label_name).strip()

                        # chỉ nhận label nằm trong ENTITY_LABELS
                        if label_name not in ENTITY_LABELS:
                            continue

                        clean_spans.append((start, min(end, len(text)), label_name))

                    # sort by length desc
                    clean_spans.sort(key=lambda x: (x[1]-x[0]), reverse=True)

                    for start, end, label_name in clean_spans:
                        b_tag = f"B-{label_name}"
                        i_tag = f"I-{label_name}"

                        # nếu chỗ start đã bị gán label khác, bỏ qua span này
                        if char_labels[start] != "O":
                            continue

                        # gán B
                        if b_tag in label2id:
                            char_labels[start] = b_tag

                        # gán I cho phần còn lại nếu còn O
                        for i in range(start + 1, end):
                            if char_labels[i] == "O" and i_tag in label2id:
                                char_labels[i] = i_tag

                    # 3) tokenize + lấy label theo ký tự đầu token
                    tokens = []
                    ner_ids = []

                    for m in TOKEN_RE.finditer(text):
                        tok = m.group()
                        s = m.start()

                        # label token = label tại ký tự đầu token
                        tok_label = char_labels[s] if s < len(char_labels) else "O"
                        tok_id = label2id.get(tok_label, 0)

                        tokens.append(tok)
                        ner_ids.append(tok_id)

                    if tokens:
                        all_ids.append(rid)
                        all_texts.append(text)
                        all_tokens.append(tokens)
                        all_ner_ids.append(ner_ids)

                except Exception as e:
                    print(f"⚠️ Error in {os.path.basename(path)} line {line_no}: {e}")
                    continue

    return all_ids, all_texts, all_tokens, all_ner_ids


# =========================
# 3) RUN
# =========================
ids, texts, tokens, ner_ids = merge_and_process_doccano(list_files)

df = pd.DataFrame({
    "id": ids,
    "text": texts,
    "tokens": tokens,
    "ner_ids": ner_ids
})

if df.empty:
    print("❌ No processed data.")
    raw_datasets = DatasetDict({})
else:
    # sanity check: tokens và ner_ids phải cùng độ dài
    bad = df[df["tokens"].apply(len) != df["ner_ids"].apply(len)]
    if len(bad) > 0:
        print("⚠️ Found length mismatch rows:", len(bad))
        df = df[df["tokens"].apply(len) == df["ner_ids"].apply(len)].reset_index(drop=True)

    train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

    raw_datasets = DatasetDict({
        "train": Dataset.from_pandas(train_df.reset_index(drop=True)),
        "test": Dataset.from_pandas(test_df.reset_index(drop=True)),
    })

    print("-" * 40)
    print("✅ DONE")
    print("Total samples:", len(df))
    print("Train:", len(train_df), "Test:", len(test_df))
    print("\nSample #1 text:\n", df.iloc[0]["text"])
    print("Sample #1 tokens:\n", df.iloc[0]["tokens"])
    print("Sample #1 ner_ids:\n", df.iloc[0]["ner_ids"])
    print("Sample #1 ner_tags:\n", [id2label[i] for i in df.iloc[0]["ner_ids"]])
    print("-" * 40)

import re

def clean_and_split_punctuation(text):
    """
    Chuẩn hóa text review Shopee:
    - tách dấu câu ra khỏi từ
    - xóa khoảng trắng thừa
    - giữ nguyên chữ tiếng Việt
    """

    if not isinstance(text, str):
        return ""

    # 1. chuẩn hóa khoảng trắng
    text = re.sub(r"\s+", " ", text).strip()

    # 2. tách dấu câu phổ biến
    text = re.sub(r'([.,!?;:()"\'])', r' \1 ', text)

    # 3. xử lý dấu ...
    text = re.sub(r'\.{2,}', ' ... ', text)

    # 4. chuẩn hóa khoảng trắng lần nữa
    text = re.sub(r"\s+", " ", text).strip()

    return text


# ---------------- TEST ----------------
input_text = "sản phẩm rất chất lượng, đáng giá với giá tiền. giao hàng nhanh chóng!"
clean_text = clean_and_split_punctuation(input_text)

print("Gốc:")
print(input_text)

print("\nSau khi xử lý:")
print(clean_text)

print("\nTokens:")
print(clean_text.split())

from transformers import AutoTokenizer, DataCollatorForTokenClassification
import numpy as np

# 1) Load tokenizer
model_checkpoint = "vinai/phobert-base"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, use_fast=True)

print("Tokenizer fast?", tokenizer.is_fast)
if not tokenizer.is_fast:
    print("⚠️ Đang dùng Slow Tokenizer. (thường do thiếu sentencepiece hoặc lỗi version)")

MAX_LEN = 256

def tokenize_and_align_labels(examples):
    """
    examples["tokens"]  : List[List[str]]
    examples["ner_ids"] : List[List[int]]
    """
    # --- sanity check (debug) ---
    # Nếu bị lỗi, in ra 1 mẫu để biết sai cấu trúc
    if "tokens" not in examples or "ner_ids" not in examples:
        raise KeyError("raw_datasets phải có cột 'tokens' và 'ner_ids'")

    # Tokenize theo word-level input
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True,
        max_length=MAX_LEN,
        padding="max_length"
    )

    aligned_labels = []

    if tokenizer.is_fast:
        # FAST: dùng word_ids
        for i, word_labels in enumerate(examples["ner_ids"]):
            word_ids = tokenized_inputs.word_ids(batch_index=i)

            label_ids = []
            prev_word_idx = None

            for word_idx in word_ids:
                if word_idx is None:
                    label_ids.append(-100)
                elif word_idx != prev_word_idx:
                    # label cho token đầu của 1 word
                    if word_idx < len(word_labels):
                        label_ids.append(word_labels[word_idx])
                    else:
                        label_ids.append(-100)
                else:
                    # token tiếp theo của cùng word -> ignore
                    label_ids.append(-100)
                prev_word_idx = word_idx

            aligned_labels.append(label_ids)

    else:
        # SLOW: tokenize từng word để biết số sub_tokens
        for i, word_labels in enumerate(examples["ner_ids"]):
            label_ids = []

            # (a) add special token đầu
            label_ids.append(-100)  # <s>

            # (b) gán label cho subword đầu, subword sau -100
            for w_idx, word in enumerate(examples["tokens"][i]):
                sub_tokens = tokenizer.tokenize(word)
                if not sub_tokens:
                    continue

                # token đầu
                if w_idx < len(word_labels):
                    label_ids.append(word_labels[w_idx])
                else:
                    label_ids.append(-100)

                # sub token còn lại
                if len(sub_tokens) > 1:
                    label_ids.extend([-100] * (len(sub_tokens) - 1))

            # (c) add special token cuối
            label_ids.append(-100)  # </s>

            # (d) pad/crop đúng MAX_LEN
            if len(label_ids) > MAX_LEN:
                label_ids = label_ids[:MAX_LEN]
            else:
                label_ids = label_ids + [-100] * (MAX_LEN - len(label_ids))

            aligned_labels.append(label_ids)

    tokenized_inputs["labels"] = aligned_labels
    return tokenized_inputs


# 3) Apply
if "raw_datasets" in globals() and len(raw_datasets) > 0:
    print("⏳ Mapping tokenize...")
    tokenized_datasets = raw_datasets.map(tokenize_and_align_labels, batched=True)

    data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

    # Debug nhanh 1 sample
    s = tokenized_datasets["train"][0]
    print("✅ Done tokenizing.")
    print("Sample keys:", s.keys())
    print("len(input_ids):", len(s["input_ids"]), "len(labels):", len(s["labels"]))
else:
    print("⚠️ Chưa có 'raw_datasets' hoặc raw_datasets rỗng. Hãy chạy bước load/convert Doccano trước.")

# Cài đặt thư viện chấm điểm
!pip install evaluate seqeval

import numpy as np
import evaluate

metric = evaluate.load("seqeval")

# =========================
# LABEL LIST (NEW) - giống lúc build label2id
# =========================
ENTITY_LABELS = [
    "KÍCH_THƯỚC",
    "MÀU_SẮC",
    "FORM",
    "CHẤT_LIỆU",
    "KỸ_THUẬT",
    "SHIP",
    "PRICE",
    "Ý_ĐỊNH",
    "CẢM_NHẬN",
]

label_list = ["O"]
for ent in ENTITY_LABELS:
    label_list += [f"B-{ent}", f"I-{ent}"]

id2label = {i: l for i, l in enumerate(label_list)}

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = []
    true_labels = []

    for pred_seq, lab_seq in zip(predictions, labels):
        cur_pred = []
        cur_lab = []
        for p_id, l_id in zip(pred_seq, lab_seq):
            if l_id == -100:
                continue
            cur_pred.append(id2label.get(int(p_id), "O"))
            cur_lab.append(id2label.get(int(l_id), "O"))
        true_predictions.append(cur_pred)
        true_labels.append(cur_lab)

    results = metric.compute(predictions=true_predictions, references=true_labels)
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

import re

def clean_tokens(token_list):
    """
    Tách dấu câu ra khỏi token.
    Ví dụ:
    "đẹp," -> ["đẹp", ","]
    "tiền." -> ["tiền", "."]
    """

    new_tokens = []

    for token in token_list:

        # regex tách word và punctuation
        parts = re.findall(r'\w+|[^\w\s]', token, flags=re.UNICODE)

        new_tokens.extend(parts)

    return new_tokens

print("✅ Kiểm tra mẫu đầu tiên:")

import collections

# id2label từ label2id (bạn đã build trước đó)
id2label = {i: l for l, i in label2id.items()}

if "tokenized_datasets" in globals() and len(tokenized_datasets.get("train", [])) > 0:
    sample = tokenized_datasets["train"][0]

    input_ids = sample["input_ids"]
    label_ids = sample["labels"]

    toks = tokenizer.convert_ids_to_tokens(input_ids)

    # 1) In token + label (bỏ special tokens / padding)
    print("\n--- TOKEN + LABEL (bỏ -100) ---")
    for t, lid in zip(toks, label_ids):
        if lid == -100:
            continue
        print(f"{t:>12}  ->  {id2label.get(int(lid), 'O')}")

    # 2) Thống kê nhãn trên toàn train (bỏ -100)
    all_label_ids = [
        l
        for row in tokenized_datasets["train"]["labels"]
        for l in row
        if l != -100
    ]
    counter_id = collections.Counter(all_label_ids)
    counter_name = collections.Counter({id2label[k]: v for k, v in counter_id.items()})

    print("\n--- THỐNG KÊ NHÃN (TRAIN) ---")
    for k, v in counter_name.most_common():
        print(f"{k:>12}: {v}")

    # 3) Cảnh báo nếu gần như toàn O
    total = sum(counter_id.values())
    o_cnt = counter_id.get(label2id["O"], 0)
    if total > 0 and o_cnt / total > 0.95:
        print("\n⚠️ Cảnh báo: >95% token là 'O'.")
        print("   Thường do:")
        print("   (1) span Doccano lệch với text sau clean/tokenize")
        print("   (2) label_name trong JSONL không khớp ENTITY_LABELS")
        print("   (3) bạn vô tình gắn nhãn cả 'màu sắc:' thay vì giá trị 'xám tiêu'")
else:
    print("⚠️ Train dataset trống hoặc chưa tạo 'tokenized_datasets'.")

def inspect_data_alignment(dataset, tokenizer, index=0, show_all=False):
    """
    dataset: tokenized_datasets["train"] hoặc ["test"]
    tokenizer: PhoBERT tokenizer
    index: dòng muốn xem
    show_all: True thì in cả special token, False thì bỏ cho gọn
    """

    # id2label lấy từ label2id mà bạn đã build trước đó
    # (phải chạy step build label2id trước)
    id2label = {i: l for l, i in label2id.items()}

    item = dataset[index]
    tokens = tokenizer.convert_ids_to_tokens(item["input_ids"])
    label_ids = item["labels"]
    attn = item.get("attention_mask", [1] * len(tokens))

    print(f"\n--- KIỂM TRA MẪU THỨ {index} ---")
    print(f"{'IDX':<4} {'TOKEN':<18} {'LABEL_ID':<8} {'LABEL_NAME':<15} {'NOTE'}")
    print("-" * 70)

    for i, (tok, lid, m) in enumerate(zip(tokens, label_ids, attn)):
        # Bỏ padding theo attention_mask (PhoBERT hay pad bằng <pad>)
        if m == 0:
            continue

        # Bỏ special token cho gọn
        if (not show_all) and tok in ["<s>", "</s>", "<pad>"]:
            continue

        if lid == -100:
            label_name = "IGN"
        else:
            label_name = id2label.get(int(lid), "UNK")

        note = ""
        # PhoBERT dùng "▁" đánh dấu bắt đầu word
        if tok.startswith("▁"):
            note = "WORD_START"
        else:
            # token không có ▁ thường là continuation subword
            if lid != -100 and label_name != "O":
                note = "⚠️ entity on subword?"

        print(f"{i:<4} {tok:<18} {str(lid):<8} {label_name:<15} {note}")

    # Thống kê nhanh % O vs entity
    valid = [l for l, m in zip(label_ids, attn) if m == 1 and l != -100]
    if valid:
        o_id = label2id["O"]
        o_rate = sum(1 for x in valid if x == o_id) / len(valid)
        print("\n--- SUMMARY ---")
        print(f"Valid tokens: {len(valid)} | O-rate: {o_rate:.2%}")
        if o_rate > 0.95:
            print("⚠️ O-rate > 95%: thường do span lệch (clean text khác text gốc) hoặc label_name không khớp.")
    else:
        print("\n⚠️ Không có token hợp lệ để thống kê (toàn -100 hoặc padding).")

# ==========================================================
# PAD / TRUNCATE VỀ 100 TOKEN

from datasets import DatasetDict
from collections import Counter

TARGET_LEN = 100
PAD_ID = tokenizer.pad_token_id

print("PAD_ID:", PAD_ID)

def pad_or_truncate_ner(example, target_len=TARGET_LEN):
    input_ids = example["input_ids"]
    labels = example["labels"]
    attention_mask = example.get("attention_mask", [1] * len(input_ids))

    # nếu dài hơn target_len thì cắt
    if len(input_ids) > target_len:
        input_ids = input_ids[:target_len]
        labels = labels[:target_len]
        attention_mask = attention_mask[:target_len]

    # nếu ngắn hơn target_len thì pad
    elif len(input_ids) < target_len:
        need = target_len - len(input_ids)
        input_ids = input_ids + [PAD_ID] * need
        labels = labels + [-100] * need
        attention_mask = attention_mask + [0] * need

    return {
        "input_ids": input_ids,
        "labels": labels,
        "attention_mask": attention_mask
    }

# áp dụng cho mọi split
tokenized_datasets_fixed100 = DatasetDict()

for split in tokenized_datasets.keys():
    tokenized_datasets_fixed100[split] = tokenized_datasets[split].map(
        pad_or_truncate_ner,
        desc=f"Padding/truncating {split} to {TARGET_LEN}"
    )

print(tokenized_datasets_fixed100)

# =========================
# KIỂM TRA 1 MẪU ĐẦU TIÊN
# =========================
sample = tokenized_datasets_fixed100["train"][0]
tokens = tokenizer.convert_ids_to_tokens(sample["input_ids"])

print("\nKiểm tra mẫu đầu tiên:")
print("Tokens:", tokens[:30])
print("Labels ID:", sample["labels"][:30])

valid_labels = [x for x in sample["labels"] if x != -100]
print("Thống kê nhãn:", Counter(valid_labels))

from transformers import AutoModelForTokenClassification

model_checkpoint = "vinai/phobert-base"  # hoặc vinai/phobert-base-v2 nếu bạn đổi

# 1) Build label_list đúng bộ nhãn mới
ENTITY_LABELS = [
    "KÍCH_THƯỚC",
    "MÀU_SẮC",
    "FORM",
    "CHẤT_LIỆU",
    "KỸ_THUẬT",
    "SHIP",
    "PRICE",
    "Ý_ĐỊNH",
    "CẢM_NHẬN",
]

label_list = ["O"]
for ent in ENTITY_LABELS:
    label_list += [f"B-{ent}", f"I-{ent}"]

label2id = {l: i for i, l in enumerate(label_list)}
id2label = {i: l for i, l in enumerate(label_list)}

# 2) Khởi tạo lại model
print("⏳ Đang tải lại Model PhoBERT...")
model = AutoModelForTokenClassification.from_pretrained(
    model_checkpoint,
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)
print("✅ Đã có Model! Số nhãn =", len(label_list))
print("Nhãn mẫu:", label_list[:8], "...")

import transformers
from transformers import TrainingArguments, Trainer

print("Transformers version:", transformers.__version__)

common_args = dict(
    output_dir="phobert-ner-finetuned",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=15,
    save_total_limit=2,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    report_to="none",
)

# 1) TrainingArguments: thử tên mới trước, fail thì rớt về tên cũ
try:
    args = TrainingArguments(**common_args, eval_strategy="epoch")
except TypeError:
    args = TrainingArguments(**common_args, evaluation_strategy="epoch")

# 2) Trainer: thử API mới trước, fail thì rớt về API cũ
try:
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets["test"],
        data_collator=data_collator,
        processing_class=tokenizer,  # transformers mới
        compute_metrics=compute_metrics,
    )
except TypeError:
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets["test"],
        data_collator=data_collator,
        tokenizer=tokenizer,         # transformers cũ
        compute_metrics=compute_metrics,
    )

print("🚀 Training...")
trainer.train()

from transformers import pipeline
import torch

print("⏳ Khởi tạo pipeline test...")

# 1) đảm bảo model + tokenizer tồn tại
assert "model" in globals(), "❌ Bạn chưa có biến model. Hãy chạy bước load/train model trước."
assert "tokenizer" in globals(), "❌ Bạn chưa có biến tokenizer. Hãy chạy bước load tokenizer trước."

# 2) set eval mode
model.eval()

# 3) chọn device tự động
use_gpu = torch.cuda.is_available()
device_id = 0 if use_gpu else -1
print("✅ Device:", "GPU" if use_gpu else "CPU")

# 4) tạo pipeline
ner_pipeline = pipeline(
    task="token-classification",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple",  # gộp B/I
    device=device_id
)
print("✅ Pipeline sẵn sàng!")

def _clean_word_phobert(w: str) -> str:
    # PhoBERT hay có '_' và '@@'
    w = w.replace("_", " ")
    w = w.replace("@@", "")
    # làm sạch khoảng trắng
    w = " ".join(w.split())
    return w.strip()

def test_predict(text: str, min_score: float = 0.5):
    print("=" * 70)
    print(f"📝 TEXT: {text}")

    results = ner_pipeline(text)

    # lọc theo score
    results = [r for r in results if r.get("score", 0) >= min_score]

    if not results:
        print("🤷 Không bắt được entity (hoặc score < ngưỡng).")
        print("=" * 70)
        return

    print(f"✅ Found {len(results)} entities (score >= {min_score}):")
    for r in results:
        ent = r.get("entity_group", r.get("entity", "UNK"))
        word = _clean_word_phobert(r.get("word", ""))
        score = r.get("score", 0)
        start = r.get("start", None)
        end = r.get("end", None)
        print(f"  - [{ent}] '{word}'  | score={score:.0%} | span=({start},{end})")

    print("=" * 70)


# ==== TEST SHOPEE
test_predict("Áo form rộng , chất nỉ lông cáo , màu xám tiêu , hình in sắt nét . màu sắc đúng , Shop giao hàng nhanh , đáng tiền .", min_score=0.5)
test_predict("Mình 1m68 58kg mặc size M vừa người , tay hơi dài . mau phai mau , giao hàng nhanh chống , Vải mềm mịn , không xù .", min_score=0.5)
test_predict("quần đẹp chất nhẹ mát mặc giấu bụng dưới đồng ý mình eo bảy mươi mặc size vừa đẹp nhé .", min_score=0.5)

# ==========================================================
# SAFE CPU PREDICT -> JSONL FOR DOCCANO
# ==========================================================

from google.colab import files
from transformers import pipeline
import pandas as pd
import json
import os
import re
import torch

print("Khởi tạo pipeline CPU...")

assert "model" in globals(), "❌ Chưa có model"
assert "tokenizer" in globals(), "❌ Chưa có tokenizer"

# Ép model sang CPU để tránh CUDA device-side assert
model.eval()
model = model.cpu()

ner_pipeline = pipeline(
    task="token-classification",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple",
    device=-1
)

print("✅ Pipeline sẵn sàng trên CPU")

# =========================
# 1) UPLOAD
# =========================
uploaded = files.upload()
input_file = list(uploaded.keys())[0]
print("📂 File:", input_file)

# =========================
# 2) LOAD TEXTS
# =========================
def pick_text_column(df):
    for c in ["text", "Text", "review", "Review", "comment", "Comment", "content", "Content", "sentence", "Sentence"]:
        if c in df.columns:
            return c
    return df.columns[0]

ext = os.path.splitext(input_file)[1].lower()
texts = []

if ext in [".xlsx", ".xls"]:
    df = pd.read_excel(input_file)
    col = pick_text_column(df)
    texts = df[col].fillna("").astype(str).tolist()

elif ext == ".csv":
    try:
        df = pd.read_csv(input_file)
    except:
        df = pd.read_csv(input_file, encoding="utf-8-sig")
    col = pick_text_column(df)
    texts = df[col].fillna("").astype(str).tolist()

elif ext == ".jsonl":
    with open(input_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                texts.append(str(obj.get("text", "")))
            except:
                texts.append("")

elif ext == ".txt":
    with open(input_file, "r", encoding="utf-8") as f:
        texts = [x.strip() for x in f]

else:
    raise ValueError("❌ Chỉ hỗ trợ .xlsx, .xls, .csv, .jsonl, .txt")

texts = [" ".join(str(x).split()) for x in texts if str(x).strip()]
print("✅ Tổng text hợp lệ:", len(texts))

# =========================
# 3) HELPER
# =========================
def clean_pred_word(w: str) -> str:
    w = str(w)
    w = w.replace("_", " ")
    w = w.replace("@@", "")
    w = " ".join(w.split())
    return w.strip()

def find_span_sequential(text, phrase, used_until=0):
    text_low = text.lower()
    phrase_low = phrase.lower().strip()

    if not phrase_low:
        return None, None

    start = text_low.find(phrase_low, used_until)
    if start == -1:
        start = text_low.find(phrase_low)

    if start == -1:
        return None, None

    end = start + len(phrase_low)
    return start, end

# =========================
# 4) PREDICT 1 TEXT
# =========================
def predict_to_doccano_record(text, rec_id, min_score=0.3):
    try:
        # cắt bớt text quá dài cho an toàn
        text = text[:600]
        results = ner_pipeline(text)
    except Exception as e:
        print(f"⚠️ Lỗi dòng {rec_id}: {e}")
        return {"id": rec_id, "text": text, "label": [], "Comments": []}

    labels = []
    used_until = 0

    for r in results:
        try:
            score = float(r.get("score", 0))
            if score < min_score:
                continue

            ent = r.get("entity_group", r.get("entity", "UNK"))
            word = clean_pred_word(r.get("word", ""))

            start = r.get("start", None)
            end = r.get("end", None)

            if start is None or end is None:
                start, end = find_span_sequential(text, word, used_until=used_until)

            if start is None or end is None:
                continue
            if not isinstance(start, int) or not isinstance(end, int):
                continue
            if start < 0 or end <= start or end > len(text):
                continue

            labels.append([start, end, ent])
            used_until = end

        except:
            continue

    # sort + dedup
    labels = sorted(labels, key=lambda x: (x[0], x[1], x[2]))
    dedup = []
    seen = set()
    for x in labels:
        key = (x[0], x[1], x[2])
        if key not in seen:
            dedup.append(x)
            seen.add(key)

    return {
        "id": rec_id,
        "text": text,
        "label": dedup,
        "Comments": []
    }

# =========================
# 5) RUN ALL
# =========================
MIN_SCORE = 0.3
output_records = []

for i, text in enumerate(texts, start=1):
    rec = predict_to_doccano_record(text=text, rec_id=i, min_score=MIN_SCORE)
    output_records.append(rec)

    if i <= 5:
        print("=" * 80)
        print("TEXT:", rec["text"])
        print("LABEL:", rec["label"])

    if i % 50 == 0:
        print(f"✔ done {i}")

print("✅ Predict xong:", len(output_records), "dòng")

# =========================
# 6) SAVE
# =========================
output_file = os.path.splitext(input_file)[0] + "_pred_doccano_cpu.jsonl"

with open(output_file, "w", encoding="utf-8") as f:
    for rec in output_records:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

print("✅ Saved:", output_file)

# =========================
# 7) DOWNLOAD
# =========================
files.download(output_file)

# ==========================================================
# SAFE CPU PREDICT -> EXPORT EXCEL DẠNG CỘT TÍN HIỆU
# CỘT XÉT: comment
# LABELS:
# KÍCH_THƯỚC, MÀU_SẮC, FORM, CHẤT_LIỆU, KỸ_THUẬT,
# SHIP, PRICE, Ý_ĐỊNH, CẢM_NHẬN
# ==========================================================

from google.colab import files
from transformers import pipeline
import pandas as pd
import json
import os
import re
import torch

print("Khởi tạo pipeline CPU...")

assert "model" in globals(), "❌ Chưa có model"
assert "tokenizer" in globals(), "❌ Chưa có tokenizer"

model.eval()
model = model.cpu()

ner_pipeline = pipeline(
    task="token-classification",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple",
    device=-1
)

print("✅ Pipeline sẵn sàng trên CPU")

# =========================
# 1) UPLOAD FILE
# =========================
uploaded = files.upload()
input_file = list(uploaded.keys())[0]
print("📂 File:", input_file)

# =========================
# 2) LOAD DATA
# =========================
def pick_text_column(df):
    priority_cols = [
        "comment", "Comment",
        "review", "Review",
        "text", "Text",
        "content", "Content",
        "sentence", "Sentence"
    ]
    for c in priority_cols:
        if c in df.columns:
            return c
    return df.columns[0]

ext = os.path.splitext(input_file)[1].lower()

if ext in [".xlsx", ".xls"]:
    df = pd.read_excel(input_file)

elif ext == ".csv":
    try:
        df = pd.read_csv(input_file)
    except:
        df = pd.read_csv(input_file, encoding="utf-8-sig")

elif ext == ".jsonl":
    rows = []
    with open(input_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                rows.append(obj)
            except:
                pass
    df = pd.DataFrame(rows)

elif ext == ".txt":
    with open(input_file, "r", encoding="utf-8") as f:
        texts = [x.strip() for x in f if str(x).strip()]
    df = pd.DataFrame({"comment": texts})

else:
    raise ValueError("❌ Chỉ hỗ trợ .xlsx, .xls, .csv, .jsonl, .txt")

text_col = pick_text_column(df)
df[text_col] = df[text_col].fillna("").astype(str)
df[text_col] = df[text_col].apply(lambda x: " ".join(x.split()))

print("✅ Cột dùng để predict:", text_col)
print("✅ Tổng số dòng:", len(df))

# =========================
# 3) LABEL MỚI CỦA BẠN
# =========================
TARGET_LABELS = [
    "KÍCH_THƯỚC",
    "MÀU_SẮC",
    "FORM",
    "CHẤT_LIỆU",
    "KỸ_THUẬT",
    "SHIP",
    "PRICE",
    "Ý_ĐỊNH",
    "CẢM_NHẬN"
]

EXPORT_COLUMN_MAP = {
    "KÍCH_THƯỚC": "KÍCH_THƯỚC",
    "MÀU_SẮC": "MÀU_SẮC",
    "FORM": "FORM",
    "CHẤT_LIỆU": "CHẤT_LIỆU",
    "KỸ_THUẬT": "KỸ_THUẬT",
    "SHIP": "SHIP",
    "PRICE": "PRICE",
    "Ý_ĐỊNH": "Ý_ĐỊNH",
    "CẢM_NHẬN": "CẢM_NHẬN"
}

# =========================
# 4) HELPER
# =========================
def clean_pred_word(w):
    w = str(w)
    w = w.replace("_", " ")
    w = w.replace("@@", "")
    w = re.sub(r"\s+", " ", w).strip()
    return w

def dedup_keep_order(lst):
    seen = set()
    out = []
    for x in lst:
        key = str(x).strip().lower()
        if key and key not in seen:
            seen.add(key)
            out.append(x)
    return out

# =========================
# 5) PREDICT 1 TEXT
# =========================
def predict_signal_columns(text, min_score=0.3, max_len=600):
    text = str(text).strip()

    empty_result = {EXPORT_COLUMN_MAP.get(lb, lb): [] for lb in TARGET_LABELS}

    if not text:
        return empty_result

    text = text[:max_len]

    try:
        results = ner_pipeline(text)
    except Exception as e:
        print(f"⚠️ Lỗi predict: {e}")
        return empty_result

    signal_dict = {EXPORT_COLUMN_MAP.get(lb, lb): [] for lb in TARGET_LABELS}

    for r in results:
        try:
            score = float(r.get("score", 0))
            if score < min_score:
                continue

            ent = r.get("entity_group", r.get("entity", "UNK"))

            # fix BIO label nếu có
            if isinstance(ent, str) and (ent.startswith("B-") or ent.startswith("I-")):
                ent = ent[2:]

            word = clean_pred_word(r.get("word", ""))

            if not word:
                continue

            if ent in TARGET_LABELS:
                out_col = EXPORT_COLUMN_MAP.get(ent, ent)
                signal_dict[out_col].append(word)

        except:
            continue

    for k in signal_dict:
        signal_dict[k] = dedup_keep_order(signal_dict[k])

    return signal_dict

# =========================
# 6) RUN ALL
# =========================
MIN_SCORE = 0.3
output_rows = []

for i, row in df.iterrows():
    text = row[text_col]

    signal_dict = predict_signal_columns(
        text=text,
        min_score=MIN_SCORE
    )

    new_row = {
        "review": text
    }

    for lb in TARGET_LABELS:
        col_name = EXPORT_COLUMN_MAP.get(lb, lb)
        new_row[col_name] = signal_dict.get(col_name, [])

    output_rows.append(new_row)

    if i < 5:
        print("=" * 80)
        print("TEXT:", text)
        print("SIGNALS:", new_row)

    if (i + 1) % 50 == 0:
        print(f"✔ done {i+1}")

print("✅ Predict xong:", len(output_rows), "dòng")

# =========================
# 7) EXPORT DATAFRAME
# =========================
out_df = pd.DataFrame(output_rows)

# ép list thành chuỗi để nhìn giống excel mẫu của bạn
for c in out_df.columns:
    if c != "review":
        out_df[c] = out_df[c].apply(lambda x: str(x) if isinstance(x, list) else "[]")

# =========================
# 8) SAVE EXCEL
# =========================
output_file = os.path.splitext(input_file)[0] + "_signals_by_comment.xlsx"
out_df.to_excel(output_file, index=False)

print("✅ Saved:", output_file)

# =========================
# 9) DOWNLOAD
# =========================
files.download(output_file)
